### ISSUE TITLE
CORS tests

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/requests#2]
Need example code and tests to make sure CORS negotiation works. See:
https://dannyda.com/2021/01/11/how-to-include-origin-in-curl-command-how-to-send-a-regular-cross-origin-resource-sharing-cors-request-using-curl/

**Comment by klemens-morgenstern** [comment]
It means i'll need to add cors support actually. Probably a good idea.

**Comment by vinniefalco** [comment]
I'm not sure about that (I don't know very much about it). But whatever we do offer, users should be able to set the appropriate headers.

**Comment by klemens-morgenstern** [comment]
Closing because CORS makes little sense for `requests` . CORS makes sense when a website makes a cross-site requests, so it would be limited to browsers.
